project:
  type: website

website:
  title: "Sharif Islam"
  navbar:
    right:
      - href: index.qmd
        text: HOME
      - href: about.qmd
        text: ABOUT
      - href: project.qmd
        text: PPROJECTS
      - href: resume/Sharif_Resume_R.pdf
        text: RESUME
      - href: books.qmd
        text: BOOKS
      - href: teaching.qmd
        text: TEACHING
      - href: blogs.qmd
        text: BLOGS
      - icon: github
        href: https://github.com/msharifbd
      - icon: twitter
        href: https://twitter.com/MSharifIslam2
  page-footer: 
     background: dark
     center: 
      - "Copyright©2025, Sharif Islam"

format:
  html:
    theme: superhero
    css: styles.css
    toc: true
    mainfont: serif



