project:
  type: website

website:
  title: "Sharif Islam"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: project.qmd
        text: Projects
      - href: resume/Sharif_Resume_R.pdf
        text: Resume
      - href: blogs.qmd
        text: Blogs
      - href: books.qmd
        text: Books
      - href: teaching.qmd
        text: Teaching
      - icon: github
        href: https://github.com/msharifbd
      - icon: twitter
        href: https://twitter.com/MSharifIslam2
  page-footer: 
     background: dark
     center: 
      - "Copyright 2024, Sharif Islam"

format:
  html:
    theme: cyborg
    css: styles.css
    toc: true
    mainfont: serif



