---
title: "About"
jupyter: python3
---

I am an Associate Professor in School of Accountancy in College of Business and Analytics in Southern Illinois University Carbondale. My teaching and research interests lie in the intersection between Accounting and Data Science. 

# Education 

* DBA Emphasis - Accounting Information Systems, Louisiana Tech University
* MBA in  Accountancy, Eastern Illinois University
* MBA in  Accounting & Information Systems, University of Dhaka 
* BBA in Accounting & Information Systems, University of Dhaka

# Professional Certification

* CPA, State of Illinois 
* CMA, Bangladesh 

# Research Interests 

* Data Breaches
* Cybersecurity
* Network Centrality of Executives
* International Accounting
* Audit Efficiency and Timeliness


# Teaching Interests 

* Auditing & Assurance Service 
* Accounting Information Systems 
* Data Analytics 
* Machine Learning 


# Hobbies 

I enjoy outdoor activities a lot, specially fishing and hiking in Southern Illinois. I like the outdoors of Southern Illinois. 