---
title: "Project"
jupyter: python3
---

# CEO Network Centrality & Audit Timeliness 
The study examines the association between CEO’s network connections and audit timeliness. Based on extant research, we hypothesize that well-connected CEOs are associated with reduced audit lag. Using a sample of over 2000 firms for the period 2004 to 2017, we find that, *ceteris paribus*, firms with well-connected CEOs are associated with reduced audit lag. We also find firms led by more connected CEOs have better financial reporting quality and pay higher auditing fees for increased audit efforts. In addition, well-connected CEO firms release 10-K reports in a timelier manner. These findings suggest that improved information environment around well-connected CEOs lead to the timely dissemination of high-quality financial information to market participants.

# Audit Committee Social Capital & Audit Fees 
The study examines the effect of audit committees connectedness, measured using network centrality from social network theory, on audit fees. We also test the effect of the same on audit quality and audit timeliness. We find that network centrality measures of audit committees are positively and significantly associated with audit fees. Moreover, we document that audit committees connectedness is associated with better financial reporting quality and audit timeliness, which might explain the increase in audit fees. We conduct several robustness tests and document the same results. Additional analysis indicates that the results are driven by the overall centrality of the audit committee and not by the centrality of committee chairs, committee financial experts, or members of the committee. Our results also hold true for both pre and post SOX period and after controlling for CEO and CFO network centrality measures. Overall, the findings suggest that connected audit committees are associated with higher audit fees because they demand better audit quality and timely dissemination of information.

# Reaction of Rival Firms to the Information Security Breach of Focal Firms: Evidence from Market Activity and Information Asymmetry 
Using competitive dynamics theory and theory of information transfer, this research examines whether there is a spillover effect from information security breaches of breached firms to those firms’ rivals. The spillover effects on rivals might be - the same as (contagion effect) or opposite (competitive effect) to - those of breached firms. The market reaction of spillover effects is measured from market activity and information asymmetry. The results suggest that the market of rival firms reacts to the breached firms’ experience of data breaches. The overall effects of data breaches on rival firms are the opposite to those to focal firms (competitive effect), although in some cases rival firms also experience negative reactions (contagion effect) in markets. Specifically, the results suggest that the characteristics of data breach types and previous data breach histories of focal firms have negative implications (contagion effect) for rivals. However, strong information technology governance of rivals plays a shielding role in mitigating those negative effects.